### ISSUE TITLE
Release new features quickly

### ISSUE THREAD

**Issue by albfan** [JohnMHarrisJr/BoogDroid#10]
I see this is published on google play:

https://play.google.com/store/apps/details?id=me.johnmh.boogdroid&hl=es

Can you publish on google play new features?

**Comment by JohnMHarrisJr** [comment]
I have long requested that the Google Play listing be taken down. Instead, I suggest installing BoogDroid through F-Droid.

https://f-droid.org/repository/browse/?fdid=me.johnmh.boogdroid

**Comment by albfan** [comment]
Ok, can I ask why take down from google play?

**Comment by JohnMHarrisJr** [comment]
Google Play is proprietary software employing DRM (Digital Restrictions Management).

**Comment by albfan** [comment]
Makes sense. What's the process to update f-droid? Can you manage to do yourself or we need to generate tags, doc, etc. I can help you with boring details if any

**Comment by JohnMHarrisJr** [comment]
I don't know yet, I've made an issue on their repo.

**Comment by albfan** [comment]
https://f-droid.org/manual/fdroid.html to speed up things or wait for them to do it

**Comment by albfan** [comment]
Why not release on our own?

https://www.reddit.com/r/github/comments/2bwa1d/this_a_stupid_question_how_do_i_upload_my_apk/

or automatically with travis

https://gist.github.com/mariotaku/7a0c51955d14def2fa0e

**Comment by JohnMHarrisJr** [comment]
That's exactly how it'll end up. The way I set it up with F-Droid it does it by Git tags.

On November 9, 2016 1:04:13 AM EST, Alberto Fanjul <notifications@github.com> wrote:
>Why not release on our own?
>
>https://www.reddit.com/r/github/comments/2bwa1d/this_a_stupid_question_how_do_i_upload_my_apk/
>
>or automatically with travis
>
>https://gist.github.com/mariotaku/7a0c51955d14def2fa0e

-- 
John M. Harris, Jr.
PGP Key: f2ea233509f192f98464c2e94f8f03c64bb38ffd

Sent from my Android device. Please excuse my brevity.

**Comment by albfan** [comment]
Ok. Just commenting because they say it has a lag in releasing if you not provide all the metadata (Indeed this is not released yet in f-droid ) Let me know if you want me to add the apk on

https://github.com/JohnMHarrisJr/BoogDroid/releases/tag/v0.0.2

That will allow people to send feedback and get traction

**Comment by JohnMHarrisJr** [comment]
If we want an apk there, I would set up a script for my local Jenkins server to upload a signed *debug* version of the application. We shouldn't be giving end user releases, only testing snapshots such as that.

On November 9, 2016 1:18:14 AM EST, Alberto Fanjul <notifications@github.com> wrote:
>Ok. Just commenting because they say it has a lag in releasing if you
>not provide all the metadata (Indeed this is not released yet in
>f-droid ) Let me know if you want me to add the apk on
>
>https://github.com/JohnMHarrisJr/BoogDroid/releases/tag/v0.0.2
>
>That will allow people to send feedback and get traction

-- 
John M. Harris, Jr.
PGP Key: f2ea233509f192f98464c2e94f8f03c64bb38ffd

Sent from my Android device. Please excuse my brevity.

**Comment by albfan** [comment]
I like the idea of create a complete workflow that covers release the apk. Travis is configured on repo so everyone forking has the complete lifecycle for the app.

Using your jenkins is for signed apps right? I feel it add a black box to the process, but do it and lets see how it goes

**Comment by JohnMHarrisJr** [comment]
On Tuesday, November 8, 2016 11:48:41 PM EST Alberto Fanjul wrote:
> I like the idea of create a complete workflow that covers release the apk.
> Travis is configured on repo so everyone forking has the complete lifecycle
> for the app.
> 
> Using your jenkins is for signed apps right? I feel it add a black box to
> the process, but do it and lets see how it goes

My Jenkins install is much less of a black box than Travic CI, which is not 
free software.

-- 
John M. Harris, Jr.
OpenBlox
https://openblox.org/

**Comment by albfan** [comment]
I mean in terms of funcionality. If someone clone this repo he has no CI by default. if we use jenkins, he cannot perform same lifecycle as we do. That way he will be confident on proposing changes. That's the main idea.

Whenever you have it integrated send me a note to see it working, right?

**Comment by JohnMHarrisJr** [comment]
@albfan If I do implement Jenkins integration, it will only build tags. I'm keeping Travis, because as bad as it is it already scales to forks too.

**Comment by albfan** [comment]
Any progress? I'm ok with google play so if you don't mind I can request a deploy there.

**Comment by JohnMHarrisJr** [comment]
@albfan I was thinking that through, and I think it's best if we just upload a debug build with each tag.

**Comment by albfan** [comment]
I did it already

https://github.com/JohnMHarrisJr/BoogDroid/releases/tag/v0.0.2
https://github.com/albfan/BoogDroid/releases/tag/0.0.2b

and share on twitter and #6.

But I can see why we cannot publish it on google play and f-droid. Is it a time matter? We can upload a beta version on markets as many apps do:

https://play.google.com/store/apps/details?id=com.chrome.beta&hl=en

**Comment by JohnMHarrisJr** [comment]
F-Droid is now set to make a build from every tag I create. I have requested to have the Google Play entry removed from their database. Google Play is non-free DRM, and it is best if I am not seen to be possibly endorsing them in any way.

On November 17, 2016 10:07:55 PM EST, Alberto Fanjul <notifications@github.com> wrote:
>I did it already
>
>https://github.com/JohnMHarrisJr/BoogDroid/releases/tag/v0.0.2
>https://github.com/albfan/BoogDroid/releases/tag/0.0.2b
>
>and share on twitter and #6.
>
>But I can see why we cannot publish it on google play and f-droid. Is
>it a time matter? We can upload a beta version on markets as many apps
>do:
>
>https://play.google.com/store/apps/details?id=com.chrome.beta&hl=en

-- 
John M. Harris, Jr.
PGP Key: f2ea233509f192f98464c2e94f8f03c64bb38ffd

Sent from my Android device. Please excuse my brevity.

**Comment by albfan** [comment]
I want to update boogdroid on android. If you can share developer console with me let me know

**Comment by JohnMHarrisJr** [comment]
The Google Play entry has been removed.

On December 19, 2016 3:19:41 PM EST, Alberto Fanjul <notifications@github.com> wrote:
>I want to update boogdroid on android. If you can share developer
>console with me let me know

-- 
John M. Harris, Jr.
PGP Key: f2ea233509f192f98464c2e94f8f03c64bb38ffd

Sent from my Android device. Please excuse my brevity.

**Comment by albfan** [comment]
Are you sure? https://play.google.com/store/apps/details?id=me.johnmh.boogdroid&hl=es

**Comment by JohnMHarrisJr** [comment]
I am sure, though if you installed it in the past, it'll still be visible I believe.

On December 19, 2016 3:23:42 PM EST, Alberto Fanjul <notifications@github.com> wrote:
>Are you sure?
>https://play.google.com/store/apps/details?id=me.johnmh.boogdroid&hl=es

-- 
John M. Harris, Jr.
PGP Key: f2ea233509f192f98464c2e94f8f03c64bb38ffd

Sent from my Android device. Please excuse my brevity.

**Comment by albfan** [comment]
Well let's stick on f-droid then. https://twitter.com/albfanjul/status/810946013292822528 I just want something aware of updates. Have to check when 0.0.3 release is done

**Comment by albfan** [comment]
I find no traction on f-droid so I release it again on google play.

https://play.google.com/store/apps/details?id=me.albfan.boogdroid

I need to change package to publish (as I don't have your keystore) So it would be hard to collaborate any further.

If you want me to change the name or something just tell me

**Comment by JohnMHarrisJr** [comment]
What's wrong with F-Droid?

**Comment by albfan** [comment]
Nothing at all. I just:

- Target maximum audience
- Want people to install apps the way they use to
- Want to know statistics about app
- Deploy app myself

**Comment by JohnMHarrisJr** [comment]
Google Play is non-free software. Many Android users, especially users who are interested in an app like this, will know the difference between a platform like Google Play and F-Droid and will avoid Google Play for this reason.

If you want statistics, ask the users. You don't need to use non-free software to track their actions, and I'm sure the users would appreciate it if you didn't do that.

I have no issues with you deploying the app, of course, so long as it's handled in a way compatible with the license of this software.

On January 29, 2017 1:31:49 AM EST, Alberto Fanjul <notifications@github.com> wrote:
>Nothing at all. I just:
>
>- Target maximum audience
>- Want people to install apps the way they use to
>- Want to know statistics about app
>- Deploy app myself

-- 
John M. Harris, Jr.
PGP Key: f2ea233509f192f98464c2e94f8f03c64bb38ffd

Sent from my Android device. Please excuse my brevity.

**Comment by albfan** [comment]
That means publish source code, right? https://github.com/albfan/BoogDroid If you have to old keystore I can stick to actual package name, but as you're against google play I think that would not happen.

If I need to change package name I think you can revoke my admin rights on your repo.

Waiting for your decision. My email is in my profile

**Comment by JohnMHarrisJr** [comment]
If it's necessary to use a separate repo to use a different package name, feel free to do that. I would appreciate it if you would contribute changes back upstream so that it's still available through F-Droid, if possible.

If you want to publish there, I'd say just change this repo to point to yours and the project is yours. I don't really have time for BoogDroid anymore anyway.

On January 29, 2017 1:56:41 AM EST, Alberto Fanjul <notifications@github.com> wrote:
>That means publish source code, right?
>https://github.com/albfan/BoogDroid If you have to old keystore I can
>stick to actual package name, but as you're against google play I think
>that would not happen.
>
>If I need to change package name I think you can revoke my admin rights
>on your repo.
>
>Waiting for your decision. My email is in my profile

-- 
John M. Harris, Jr.
PGP Key: f2ea233509f192f98464c2e94f8f03c64bb38ffd

Sent from my Android device. Please excuse my brevity.
