### ISSUE TITLE
Search Feature

### ISSUE THREAD

**Issue by AntumDeluge** [JohnMHarrisJr/BoogDroid#4]
I don't see a search feature in BoogDroid. This makes it very difficult to find specific indexes. If it doesn't already have a feature like this I think it would be a very good idea.

**Comment by JohnMHarrisJr** [comment]
I don't see any reason that I couldn't implement such a feature, when I find the time. The issue comes down to supporting the various versions of Bugzilla, whether I'd be webscraping the results of a search or using the newer API.

**Comment by albfan** [comment]
See #8
