### ISSUE TITLE
implement edit features

### ISSUE THREAD

**Issue by albfan** [JohnMHarrisJr/BoogDroid#9]
I want to implement edit features: Change status, add comment. I suppose it will be related with your ownership of the task, etc.

Any progress on this?

Documentation:
https://www.bugzilla.org/docs/4.4/en/html/api/Bugzilla/WebService/Bug.html#Bug_Creation_and_Modification

**Comment by albfan** [comment]
I have push access, Let's work on this. Any particular workflow to develop and integrate new features?

**Comment by JohnMHarrisJr** [comment]
Not specifically. I like to keep master stable, but that's really all. Atomic commits are nice, if that's not too much trouble.

Currently, I don't even have an environment set up where I can work on this. I'm working on that now, in fact.

**Comment by albfan** [comment]
I'm using an old laptop with arch linux and android studio 2.2. Some app hangs due to memory ram but reasonably stable.

**Comment by JohnMHarrisJr** [comment]
I'm on a laptop with Gentoo GNU/Linux-libre and GNU Emacs. I'm building with Gradle.

On November 8, 2016 12:07:36 PM EST, Alberto Fanjul <notifications@github.com> wrote:
>I'm using an old laptop with arch linux and android studio 2.2. Some
>app hangs due to memory ram but reasonably stable.

-- 
John M. Harris, Jr.
PGP Key: f2ea233509f192f98464c2e94f8f03c64bb38ffd

Sent from my Android device. Please excuse my brevity.

**Comment by albfan** [comment]
I will work on change state and add comment first. Any ideas about layout or design to choose?

**Comment by albfan** [comment]
Add comment will be a textarea avaliable at the bottom and change status (or anything you're allow to would be a swipe tab on bug view http://www.androidhive.info/2015/09/android-material-design-working-with-tabs/

I would love to add a left lateral menu to pin your favourite issues or products

**Comment by albfan** [comment]
I will keep open only the PR #11 for updates
